#!/usr/bin/env python3
from optparse import OptionParser
from imageio import imread
from lettucethink import fsdb
from scanner import localdirs
from processing.masking import compute_mask_TGI

if __name__ == "__main__":
    usage = "usage: %prog [options] SCAN_ID"
    parser = OptionParser(usage=usage)

    parser.add_option("-t", "--threshold",
        dest="t",
        default=0.5,
        type="float",
        help ="threshold for segmentation")

    (options, args) = parser.parse_args()
    if len(args) < 1:
        print("Missing argument : SCAN_ID")
        parser.exit(1)

    scan_id = args[0]

    db_dir = localdirs.db_dir
    db = fsdb.DB(db_dir)
    scan = db.get_scan(scan_id)
    fileset = scan.get_fileset("images")
    fs=fileset.get_files()

    fileset_masks = scan.get_fileset("masks")
    if fileset_masks is None:
        fileset_masks = scan.create_fileset("masks")

    for f in fs:
        image = f.read_image()
        mask = compute_mask_TGI(image, options.t)
        mask_file = fileset_masks.get_file(f.id)
        if mask_file is None:
            mask_file = fileset_masks.create_file(f.id)
        mask_file.write_image("png", mask)
