[build-system]
requires = ["setuptools >=75"]
build-backend = "setuptools.build_meta"

[project]
name = "plant3dvision"
version = "0.13.1"
dependencies = [
    "pywavefront",
    "trimesh",
    "appdirs",
    "colorlog",
    "docker",
    "imageio>= 2.16.2",
    "imagecodecs",
    "pandas",
    "networkx",
    "open3d>= 0.9.0.0",
    "opencv-contrib-python",
    "pybind11",
    "pyopencl",
    "scikit-image",
    "toml",
    "joblib",
    "matplotlib",
    "dash",
    "dash-iconify",
]
description = "3D reconstruction & quantification of single potted plants from RGB scans."
readme = "README.md"
requires-python = ">=3.8"
license = { 'text' = "LGPL-3.0-or-later" }   # to replace by "LGPL-3.0-or-later" only in next release, pending deprecation
authors = [
    { name = "Peter Hanappe", email = "peter.hanappe@sony.com" },
    { name = "Timothée Wintz", email = "timothee@timwin.fr" },
    { name = "Nabil Ait Taleb", email = "mohamednabil.aittaleb@sony.com" },
]
maintainers = [
    { name = "Jonathan Legrand", email = "jonathan.legrand@ens-lyon.fr" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]
keywords = [
    "Robotics for Microfarms",
    "ROMI",
    "photogrammetry",
    "SfM",
    "COLMAP",
    "pipeline",
]

[project.scripts]
check_measures = "bin.check_measures:main"
colmap_poses = "bin.colmap_poses:main"
create_charuco_board = "bin.create_charuco_board:main"
volume_viewer = "bin.volume_viewer:main"
robustness_evaluation = "bin.robustness_evaluation:main"
voronoi_texture_generator = "bin.voronoi_texture_generator:main"

[project.urls]
homepage = "https://romi-project.eu/"
documentation = "https://docs.romi-project.eu/plant_imager/"
source = "https://github.com/romi/plant-3d-vision"
issues = "https://github.com/romi/plant-3d-vision/issues"

[project.optional-dependencies]
doc = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "pymdown-extensions",
    "markdown-exec[ansi]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
]

webterm = [
    "flask",
    "flask-socketio",
    "eventlet",
    "passlib",
    "python-engineio",
    "python-socketio",
]

[tool.setuptools]
packages = [
    "romitask",
    "plantdb",
    "plant3dvision",
    "romicgal",
    "romiseg",
    "dtw",
    "skeleton_refinement",
]
include-package-data = true  # Includes files from MANIFEST.in