services:
  plantdb:
    image: "roboticsmicrofarms/plantdb:latest"
    user: "${user}:${gid}"
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - ${romi_db}:/myapp/db
    command: "fsdb_rest_api --port 5000"

  plant3dvision:
    container_name: plant3dvision
    image: "roboticsmicrofarms/plant-3d-vision:0.13.1-cuda_cc75"
    user: "${user}:${gid}"
    environment:
      - PYOPENCL_CTX=0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - app_network
    volumes:
      - ${romi_db}:/myapp/db
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
    command: bash

  webterm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_RUN_HOST=0.0.0.0  # listen on all interfaces
      - REST_API_BASE_URL=http://plantdb:5000
      - TERMINAL_CONTAINER=plant3dvision
      - CONTAINER_USER=${user}
    depends_on:
      - plantdb
      - plant3dvision
    networks:
      - app_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Required for Docker API access

networks:
  app_network:
    driver: bridge