{% set pyproject = load_file_data('../../pyproject.toml', 'toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project', {}) %}
{% set deps = project.get('dependencies', {}) %}
{% set urls = project.get('urls', {}) %}
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# Source code for Jinja context: https://github.com/conda/conda-build/blob/main/conda_build/jinja_context.py
# Then search for the `load_file_data` function.

package:
  name: {{ project.get('name') }}
  version: {{ project.get('version') }}

source:
  path: ../../  # to build from cloned sources

build:
  noarch: python  # Build as a platform-independent Python package
  script: python -m pip install .

requirements:
  build:
    - setuptools
    - python  {{ project.get('requires-python') }}  # Minimum Python version requirement from pyproject.toml
  host:
    - python  {{ project.get('requires-python') }}  # Minimum Python version requirement from pyproject.toml
  run:
    - python  {{ project.get('requires-python') }}  # Minimum Python version requirement from pyproject.toml
    - numpy >=2
    {% for dep in deps %}
    {% if not dep.startswith('open3d') %}
    - {{ dep }}
    {% endif %}
    {% endfor %}

about:
  home: {{ urls.get('Homepage') }}
  summary: {{ project.get('description') }}
  dev_url: {{ urls.get('Repository') }}
  license: LGPL-3.0-or-later
  license_file: LICENSE
  description: |
    The _3D plant phenotyping platform_ of the ROMI project allows to performs a full 3D analysis of plants.
    It combines an imaging station with a powerful image processing pipeline, to build a 3D representation of plants.
    This package act as the main data processing workflow and require other ROMI libraries.
