[Voxels]
upstream_mask = "ImagesFilesetExists"
upstream_colmap = "DummyTask"
query = "{\"channel\":\"background\"}"
camera_metadata = "camera"
voxel_size = 0.05
type = "carving"
log = false
invert = true

[PointCloud]
upstream_task = "Voxels"
level_set_value = 0.0

[TriangleMesh]
upstream_task = "PointCloud"
library = "open3d" # or "cgal"
filtering = "most connected triangles"  # ["", "most connected triangles", "largest connected triangles", "dbscan point-cloud"]

[CurveSkeleton]
upstream_task = "TriangleMesh"

[TreeGraph]
upstream_task = "CurveSkeleton"
z_axis = 2
stem_axis_inverted = false

[AnglesAndInternodes]
upstream_task = "TreeGraph"
characteristic_length = 1.0
stem_axis_inverted = false

[Visualization]
use_colmap_poses = false
upstream_virtualplantobj = "VirtualPlantObj"
query = "{\"channel\":\"rgb\"}"  # default is an empty dict '{}'

### Evaluation ####

## PointCloud
[PointCloudGroundTruth]
upstream_task = "VirtualPlantObj" # The dataset must have an obj in VirtualPlant
pcd_size = 100000 # default 100000

[PointCloudEvaluation]
upstream_task = "PointCloud"
ground_truth = "PointCloudGroundTruth"
max_distance = 2.0 # default to 2.0

## AnglesAndInternodes
[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "VirtualPlantObj"
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
no_confirm = true
