[ModelFileset]
scan_id = "models"

[Segmentation2D]
upstream_task = "ImagesFilesetExists"
model_fileset = "ModelFileset"
model_id = "Resnet_896_896_epoch50"  # no default value
query = "{\"channel\":\"rgb\"}"  # default is an empty dict '{}'
Sx = 896
Sy = 896
binarize = true
resize = true
dilation = 1
epochs = 1
batch = 1
learning_rate = 0.0001
threshold = 0.01

[Voxels]
upstream_mask = "Segmentation2D"
use_colmap_poses = false
voxel_size = 0.3
type = "averaging"
log = false # default to true
invert = false
labels = "[\"background\", \"fruit\", \"leaf\", \"pedicel\", \"stem\"]"

[PointCloud]
upstream_task = "Voxels"
level_set_value = 0.5 # default to 1.0
log = false
background_prior= 1.0
min_contrast = 1.0
min_score = 0.01 # default to 0.2

[SegmentedPointCloud]
upstream_segmentation = "Segmentation2D"
upstream_task = "PointCloud"
use_colmap_poses = false

[ClusteredMesh]
upstream_task = "SegmentedPointCloud"
min_vol = 1.0
min_length = 10.0

[OrganSegmentation]
upstream_task = "SegmentedPointCloud"
eps = 2.0
min_points = 5

[AnglesAndInternodes]
upstream_task = "OrganSegmentation"
characteristic_length = 1.0
organ_type = "fruit"
stem_axis = 2
stem_axis_inverted = false
min_elongation_ratio = 2.0
min_fruit_size = 0.1

[Visualization]
upstream_point_cloud = "PointCloud"
upstream_mesh = "TriangleMesh"
upstream_colmap = "Colmap"
upstream_angles = "AnglesAndInternodes"
upstream_skeleton = "CurveSkeleton"
upstream_images = "ImagesFilesetExists"
max_image_size = 1500
max_point_cloud_size = 10000
thumbnail_size = 150

### Evaluation ###

## PointCloud
[PointCloudGroundTruth]
upstream_task = "VirtualPlantObj" # The dataset must have an obj in VirtualPlant
pcd_size = 100000 # default 100000

[PointCloudEvaluation]
upstream_task = "PointCloud"
ground_truth = "PointCloudGroundTruth"
max_distance = 2.0 # default to 2.0

## Segmentation2D
[Segmentation2DEvaluation]
upstream_task = "Segmentation2D"
labels = "[\"flower\", \"fruit\", \"leaf\", \"pedicel\", \"stem\"]"
dilation_amount = 0

## SegmentedPointCloud
[SegmentedPointCloudEvaluation]
upstream_task = "SegmentedPointCloud"
ground_truth = "PointCloudGroundTruth"

[Clean]
no_confirm = true
