[Colmap]
matcher = "exhaustive"
compute_dense = false

[Colmap.cli_args.feature_extractor]
"--ImageReader.single_camera" = "1"
"--SiftExtraction.use_gpu" = "1"

[Colmap.cli_args.exhaustive_matcher]
"--SiftMatching.use_gpu" = "1"

[Colmap.cli_args.model_aligner]
"--robust_alignment_max_error" = "10"

[accessory]
calibration_scan_id = "calib_scan_shortpath"

[Masks]
upstream_task = "ImagesFilesetExists"
#upstream_task = "Undistorted"  # other option
type = "linear"
parameters = "[0,1,0]"
dilation = 5
binarize = true
threshold = 0.3

[Voxels]
upstream_mask = "Masks"
multiclass = false
voxel_size = 1.0
type = "averaging"
use_colmap_poses = true
log = false

[PointCloud]
upstream_task = "Voxels"
level_set_value = 0.5
background_prior= -200

[TriangleMesh]
upstream_task = "PointCloud"

[CurveSkeleton]
upstream_task = "TriangleMesh"

[TreeGraph]
upstream_task = "CurveSkeleton"

[AnglesAndInternodes]
upstream_task = "TreeGraph"

[Visualization]
max_image_size = 1500
max_pcd_size = 10000
thumbnail_size = 150
pcd_source = "vox2pcd"
mesh_source = "delaunay"

[Clean]
no_confirm = true
