[Colmap]
# Type of matcher to use with COLMAP
# Options: "exhaustive" (matches every image against every other) or "sequential" (matches successive images)
matcher = "exhaustive"  # Default: "exhaustive"
# Camera model to use for reconstruction
# Options: "SIMPLE_RADIAL", "RADIAL", "OPENCV"
camera_model = "SIMPLE_RADIAL"  # Default: "SIMPLE_RADIAL"
# Whether images were taken with a single camera (shared intrinsics)
single_camera = true  # Default: true
# Whether to perform the verification of the estimated camera extrinsic
qc_check = true
# Median absolute deviation factor to detect outlier camera pose
mad_factor = 3.0
# The list of metrics to use to detect the outliers using the MAD method.
metrics = '["xy", "z", "pan", "roll"]'
# Maximum distance to CNC pose to validate COLMAP pose estimation
distance_threshold = 3.0  # Default: 3.0mm
# Maximum distance to fixed CNC pose to validate COLMAP pose estimation
fixed_distance_threshold = 1.0  # Default: 1.0mm
# Maximum angular distance to CNC pose to validate COLMAP pose estimation
angle_threshold = 5.0  # Default: 5.0°
# Maximum angular distance to fixed CNC pose to validate COLMAP pose estimation
fixed_angle_threshold = 3.5  # Default: 3.5°
# Maximum blind angle tolerated for camera pose quality control
max_blind_angle = 20.0  # Default: 20.0 (degrees)
# Number of retries if the task fails
retry_count = 10  # Default: 10

[Undistort]
# The upstream task that provides the input files
upstream_task = "ImagesFilesetExists"  # Default: "ImagesFilesetExists"
# Query to filter files from upstream task by metadata
query = "{}"  # Default: "{}"  (empty dictionary, no filtering)
# Source of the camera model
# Options: 'Colmap', 'IntrinsicCalibration', 'ExtrinsicCalibration'
camera_model_src = "Colmap"  # Default: "Colmap"

[Masks]
# The upstream task that provides input images
# Options: "Undistort", "ImagesFilesetExists"
upstream_task = "Undistort"  # Default: "Undistort"
# Query to filter files from upstream task by metadata
query = "{\"channel\":\"rgb\"}"  # Default: "{\"channel\":\"rgb\"}"  (only RGB images)
# The type of image transformation algorithm to use prior to masking
# Options: "linear" (linear combination of RGB channels), "excess_green" (excess green index)
method = "linear"  # Default: "linear"
# The colorspace to use for the filtering
# Options: "RGB", "HSV", "YCbCr"
colorspace = "RGB"  # Default: "RGB"
# Linear coefficients to apply to each channel of the original image in the selected colorspace
# Used only when type="linear"
parameters = "[0.2, 1, 0.1]"  # Default: [0, 1, 0] (using only the green channel in RGB)
# Binarization threshold applied after transforming the image
min_threshold = 0.2 # Default: 0.0
max_threshold = 1.0 # Default: 0.4

[Voxels]
# Task that provides the masked images as input
upstream_task = "Masks"  # Default: "Masks"
# Query to filter files from upstream task by metadata
# Default: "{}"  (empty dictionary, no filtering)
# query = "{\"pose_estimation\":\"correct\"}"  # mask with a valid COLMAP pose if `type="carving"`
query = "{}" # all masks may be used with `type="averaging"`, even those with incorect pose estimates by Colmap
# Size of the voxel to reconstruct, defines the resolution of the 3D array
voxel_size = 1.0  # Default: 1.0
# Type of backprojection algorithm to use
# Options: "carving", "averaging"
method = "averaging"  # Default: "averaging"

[Voxels.bounding_box]
# 3D bounding box defining the region of interest for reconstruction
# Default: None (uses the entire volume)
# The values works with the 'real_plant' test data
x = [330, 450]
y = [300, 430]
z = [-125, 100]

[PointCloud]
# Task that provides the voxel array as input
upstream_task = "Voxels"  # Default: "Voxels"
# The algorithm to use to compute the pointcloud
algorithm = "marching-cubes"  # Default: "marching-cubes"
# Threshold for the number of missing images allowed in the reconstruction
missing_images_threshold = 2  # Default: 2
# Standard deviation for Gaussian kernel (only for marching-cubes)
sigma = 0.8
# Level set value for the marching cubes algorithm
mc_level = 0.5

[TriangleMesh]
# Task that provides the point cloud as input
upstream_task = "PointCloud"  # Default: "PointCloud"
# The library to use for meshing the point cloud
# Options: 'open3d', 'cgal'
library = "open3d"  # Default: "open3d"
# Filtering method to apply to the obtained triangle mesh
# Options: "", "most connected triangles", "largest connected triangles", "dbscan point-cloud"
filtering = "most connected triangles"  # Default: "most connected triangles"
# Depth parameter used by Open3D to mesh the point cloud
# Only used if library = "open3d"
depth = 9  # Default: 9

[CurveSkeleton]
# Task that provides the triangle mesh as input
upstream_task = "TriangleMesh"  # Default: "TriangleMesh"

[TreeGraph]
# Task that provides the skeleton data as input
upstream_task = "RefineSkeleton"  # Default: "RefineSkeleton"
# Axis to use for stem orientation to determine the root node
# Options: 0 (x-axis), 1 (y-axis), 2 (z-axis)
z_axis = 2  # Default: 2 (z-axis)
# Whether the direction of the stem along the specified axis is inverted
stem_axis_inverted = false  # Default: false

[AnglesAndInternodes]
# Task that provides the input data for angle and internode measurements
# Options: "TreeGraph", "ClusteredMesh", "OrganSegmentation"
upstream_task = "TreeGraph"  # Default: "TreeGraph"
# Minimum size (in millimeters) for an organ to be considered as a fruit
# Used with all upstream task types
min_fruit_size = 8.0  # Default: 6.0
# Distance for node sampling along the skeleton
node_sampling_dist = 10.0  # Default: 10.0
# Type of organs to analyze when using ClusteredMesh or OrganSegmentation as upstream task
organ_type = "fruit"  # Default: "fruit"

[PlantMetrics]
# The upstream task that provides the input files
upstream_task = "ImagesFilesetExists"  # Default: "ImagesFilesetExists"
# The list of matrics to compute
metrics = ["stem_length", "q_hull_volume"]

# --------------- Evaluation --------------- #
[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "ImagesFilesetExists"  # "ImagesFilesetExists" with manual measures / "VirtualPlantObj" with computer generated plants
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
# Whether NOT to ask for confirmation prior to cleaning a dataset
no_confirm = true  # Default: false