[Voxels]
upstream_mask = "ImagesFilesetExists"
upstream_colmap = "DummyTask"
query = "{\"channel\":\"background\"}"  # use the (inverted) background masks
camera_metadata = "camera"
voxel_size = 0.06  # ~9x smaller than real plants
type = "carving"
invert = true

[PointCloud]
upstream_task = "Voxels"
level_set_value = 0.0

[TriangleMesh]
upstream_task = "PointCloud"
library = "open3d" # or "cgal"
filtering = "most connected triangles"  # ["", "most connected triangles", "largest connected triangles", "dbscan point-cloud"]
depth = 9  # depth parameter used by Open3D to mesh the point cloud

[CurveSkeleton]
upstream_task = "TriangleMesh"

[RefineSkeleton]
upstream_task = "CurveSkeleton"
upstream_pcd = "PointCloud"
alpha = 5.0
beta = 5.0
knn_mst = true

[TreeGraph]
upstream_task = "RefineSkeleton"
z_axis = 2
stem_axis_inverted = false

[AnglesAndInternodes]
upstream_task = "TreeGraph"
characteristic_length = 1.0
stem_axis_inverted = false
organ_type = "fruit"
node_sampling_dist = 2  # ~9x smaller than real plants
min_fruit_size = 0.7  # ~9x smaller than real plants

[Visualization]
upstream_images = "ImagesFilesetExists"
upstream_point_cloud = "PointCloud"
upstream_mesh = "TriangleMesh"
upstream_skeleton = "CurveSkeleton"
upstream_angles = "AnglesAndInternodes"
upstream_virtualplantobj = "VirtualPlantObj"
query = "{\"channel\":\"rgb\"}"  # default is an empty dict '{}'
max_image_size = 1500
max_point_cloud_size = 10000000
thumbnail_size = 150
use_colmap_poses = false

# --------------- Evaluation --------------- #
[PointCloudGroundTruth]
upstream_task = "VirtualPlantObj" # The dataset must have an obj in VirtualPlant
pcd_size = 100000 # default 100000

[PointCloudEvaluation]
upstream_task = "PointCloud"
ground_truth = "PointCloudGroundTruth"
max_distance = 2.0 # default to 2.0

[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "VirtualPlantObj"
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
no_confirm = true
