[Colmap]
upstream_task = "ImagesFilesetExists"
matcher = "exhaustive"
camera_model = "SIMPLE_RADIAL"
intrinsic_calibration_scan_id = ""  # use a dataset with calibrated intrinsic camera poses
extrinsic_calibration_scan_id = ""  # use a dataset with calibrated extrinsic camera poses
compute_dense = false
align_pcd = true
use_gpu = true
single_camera = true
alignment_max_error = 10
distance_threshold = 5  # maximum allowed Euclidean distance from CNC pose
# [Colmap.bounding_box]  # default to None
# x = [150, 650]
# y = [150, 650]
# z = [-90, 300]

[Undistorted]
upstream_task = "ImagesFilesetExists"
query = "{\"channel\":\"rgb\", \"pose_estimation\":\"correct\"}"  # RGB images with a valid COLMAP pose

[Masks]
upstream_task = "Undistorted"
type = "linear"
parameters = "[0, 1, 0]"
dilation = 3 # default to 0
binarize = true
threshold = 0.15

[Voxels]
upstream_mask = "Masks"
upstream_colmap = "Colmap"
camera_metadata = "colmap_camera"
voxel_size = 0.5
type = "carving"
[Voxels.bounding_box]  # default to None
x = [300, 450]
y = [300, 450]
z = [-175, 100]

[PointCloud]
upstream_task = "Voxels"
level_set_value = 1.0

[TriangleMesh]
upstream_task = "PointCloud"
library = "open3d" # or "cgal"
filtering = "most connected triangles"  # ["", "most connected triangles", "largest connected triangles", "dbscan point-cloud"]
depth = 9  # depth parameter used by Open3D to mesh the point cloud

[CurveSkeleton]
upstream_task = "TriangleMesh"

[RefineSkeleton]
upstream_task = "CurveSkeleton"
upstream_pcd = "PointCloud"
alpha = 5.0
beta = 5.0
knn_mst = true

[TreeGraph]
upstream_task = "RefineSkeleton"
z_axis = 2
stem_axis_inverted = false

[AnglesAndInternodes]
upstream_task = "TreeGraph"
characteristic_length = 1.0
stem_axis_inverted = false
organ_type = "fruit"
node_sampling_dist = 10  # path distance from branching point in millimeters
min_fruit_size = 8  # path distance from branching point in millimeters

[Visualization]
upstream_images = "ImagesFilesetExists"
upstream_colmap = "Colmap"
upstream_point_cloud = "PointCloud"
upstream_mesh = "TriangleMesh"
upstream_skeleton = "CurveSkeleton"
upstream_angles = "AnglesAndInternodes"
max_image_size = 1500
max_point_cloud_size = 10000000
thumbnail_size = 150
use_colmap_poses = true

# --------------- Evaluation --------------- #
[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "ImagesFilesetExists"  # "ImagesFilesetExists" with manual measures / "VirtualPlantObj" with computer generated plants
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
no_confirm = true
