[Colmap]
upstream_task = "ImagesFilesetExists"
matcher = "exhaustive"
intrinsic_calibration_scan_id = ""
extrinsic_calibration_scan_id = ""
compute_dense = false
align_pcd = true
use_gpu = true
single_camera = true
robust_alignment_max_error = 10
distance_threshold = 4
retry_count = 10

[Undistorted]
upstream_task = "ImagesFilesetExists"
query = "{\"channel\":\"rgb\", \"pose_estimation\":\"correct\"}"  # RGB images with a valid COLMAP pose

[ModelFilesetExists]
scan_id = "models"

[Segmentation2D]
upstream_task = "Undistorted"
model_fileset = "ModelFilesetExists"
model_id = "Resnet_896_896_epoch50"  # no default value
query = "{\"channel\":\"rgb\"}"  # default is an empty dict '{}'
Sx = 896
Sy = 896
binarize = true
resize = true
dilation = 1
epochs = 1
batch = 1
learning_rate = 0.0001
threshold = 0.01

[Voxels]
upstream_task = "Segmentation2D"
voxel_size = 1
type = "averaging"
invert = true
threshold = -100.0
labels = "[\"background\"]"

[Voxels.bounding_box]
# Needs to be defined according to scanned data
x = [ 300, 435,]
y = [ 300, 435,]
z = [ -300, 60,]

[PointCloud]
upstream_task = "Voxels"
labels = "[\"background\"]"
level_set_value = 0.5 # default to 1.0
log = false
background_prior= 1.0
min_contrast = 10.0
min_score = 0.01 # default to 0.2

[SegmentedPointCloud]
upstream_task = "PointCloud"
upstream_segmentation = "Segmentation2D"
use_colmap_poses = true

[ClusteredMesh]
upstream_task = "SegmentedPointCloud"
min_vol = 1.0
min_length = 10.0

[OrganSegmentation]
upstream_task = "SegmentedPointCloud"
eps = 2.0
min_points = 5

[AnglesAndInternodes]
upstream_task = "OrganSegmentation"
characteristic_length = 1.0
organ_type = "fruit"
stem_axis = 2
stem_axis_inverted = false
min_elongation_ratio = 2.0
min_fruit_size = 0.1

[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "ImagesFilesetExists"  # "ImagesFilesetExists" with manual measures / "VirtualPlantObj" with computer generated plants
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
no_confirm = true
