[ModelFilesetExists]
scan_id = "models"

[Segmentation2D]
upstream_task = "ImagesFilesetExists"
model_fileset = "ModelFilesetExists"
model_id = "Resnet_896_896_epoch50"  # no default value
query = "{\"channel\":\"rgb\"}"  # default is an empty dict '{}'
binarize = true
dilation = 0

[Voxels]
upstream_task = "Segmentation2D"
camera_metadata = "camera"  # serach directly in 'images' metadata
voxel_size = 0.3
method = "averaging"
labels = "[\"background\"]"  # use the (inverted) background masks
invert = true
[Voxels.bounding_box]
x = [-15, 35]
y = [-15, 35]
z = [-5, 125]


[PointCloud]
upstream_task = "Voxels"
labels = "[\"background\"]"
min_agreement = 0.95
algorithm = "marching-cubes"  # Default: "marching-cubes"
level_set_value = 0.0
sigma = 0.8
mc_level = 0.5

[SegmentedPointCloud]
upstream_segmentation = "Segmentation2D"
upstream_task = "PointCloud"
use_colmap_poses = false

[ClusteredMesh]
upstream_task = "SegmentedPointCloud"
min_vol = 1.0
min_length = 10.0

[OrganSegmentation]
upstream_task = "SegmentedPointCloud"
eps = 2.0
min_points = 5

[AnglesAndInternodes]
upstream_task = "OrganSegmentation"
characteristic_length = 1.0
organ_type = "fruit"
stem_axis = 2
stem_axis_inverted = false
min_elongation_ratio = 2.0
min_fruit_size = 0.1

### Evaluation ###

## PointCloud
[PointCloudGroundTruth]
upstream_task = "VirtualPlantObj" # The dataset must have an obj in VirtualPlant
pcd_size = 100000 # default 100000

[PointCloudEvaluation]
upstream_task = "PointCloud"
ground_truth = "PointCloudGroundTruth"
max_distance = 2.0 # default to 2.0

## Segmentation2D
[Segmentation2DEvaluation]
upstream_task = "Segmentation2D"
labels = "[\"flower\", \"fruit\", \"leaf\", \"pedicel\", \"stem\"]"
dilation_amount = 0

## SegmentedPointCloud
[SegmentedPointCloudEvaluation]
upstream_task = "SegmentedPointCloud"
ground_truth = "PointCloudGroundTruth"

## AnglesAndInternodes
[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "VirtualPlantObj"
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
no_confirm = true
