[Colmap]
upstream_task = "ImagesFilesetExists"
# colmap_exe = "none"  # Let the default choice work, will be 'colmap' in docker container
matcher = "exhaustive"
use_gpu = true
single_camera = true
compute_dense = false
alignment_max_error = 10
align_pcd = true
camera_model = "SIMPLE_RADIAL"
qc_check = true
mad_factor = 3.0
metrics = '["xy", "z"]'
distance_threshold = 3.0
fixed_distance_threshold = 1.0
angle_threshold = 5.0
fixed_angle_threshold = 3.5
max_blind_angle = 25.0

[Undistort]
upstream_task = "ImagesFilesetExists"
query = "{\"channel\":\"rgb\", \"pose_estimation\":\"correct\"}"  # RGB images with a valid COLMAP pose

[Masks]
upstream_task = "Undistort"
query = "{\"channel\":\"rgb\"}"
method = "linear"
colorspace = "RGB"
parameters = "[0.2, 1, 0.1]"
min_threshold = 0.2 # Default: 0.0
max_threshold = 1.0 # Default: 0.4
dilation = 1 # Default: 0 (no dilation)

[Voxels]
upstream_task = "Masks"
upstream_colmap = "Colmap"
camera_metadata = "colmap_camera"
voxel_size = 0.6
method = "averaging"
[Voxels.bounding_box]
x = [300, 450]
y = [300, 450]
z = [-175, 105]

[PointCloud]
upstream_task = "Voxels"
missing_images_threshold = 2  # Default: 2
algorithm = "marching-cubes"  # Default: "marching-cubes"
level_set_value = 1.0
sigma = 0.8
mc_level = 0.5

[TriangleMesh]
upstream_task = "PointCloud"
library = "open3d"
filtering = "most connected triangles"

[CurveSkeleton]
upstream_task = "TriangleMesh"

[TreeGraph]
upstream_task = "CurveSkeleton"
z_axis = 2
stem_axis_inverted = false

[AnglesAndInternodes]
upstream_task = "TreeGraph"
characteristic_length = 1.0
stem_axis_inverted = false

[AnglesAndInternodesEvaluation]
upstream_task = "AnglesAndInternodes"
ground_truth = "ImagesFilesetExists"
free_ends = 0.4
free_ends_eps = 1e-2

[Clean]
no_confirm = true
