services:

  runner:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_RUNNER_URL: ${GITHUB_RUNNER_URL}
        GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
        GITHUB_RUNNER_LABELS: ${GITHUB_RUNNER_LABELS:-self-hosted,linux,docker,x64}
        GITHUB_RUNNER_NAME: ${GITHUB_RUNNER_NAME:-romi-github-runner}

    image: self-hosted-runner:latest
    container_name: romi-github-runner
    # DinD requires privileged mode for the inner Docker daemon
    privileged: true
    restart: always

    volumes:
      - runner-cache:/actions-runner/_work
      - runner-certs:/usr/share/ca-certificates

    environment:
      - GITHUB_RUNNER_EPHEMERAL=true

    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1

volumes:
  runner-cache:
  runner-certs: