# This workflow will build the Docker image, run python unit tests and checks if main features of the pipe are not broken

name: CI

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

jobs:
    docker-build:
        runs-on: self-hosted

        steps:
         - uses: actions/checkout@v2
         - name: Build Dockerfile
           run: |
            cd docker/
            docker build -t romiscan:latest --build-arg USER_NAME=$(id -n -u) --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) .
    
    unit-tests:
        runs-on: self-hosted
        needs: docker-build
        
        steps:
         - name: Run Unit Tests
           run: |
            docker run --gpus all -t --rm romiscan:latest bash
            pytest romiscan/tests/
            exit
    
    feature-tests:
        runs-on: self-hosted
        needs: docker-build
        
        steps:
         - name: Check Pipe
           run: |
            docker run --gpus all -t --rm romiscan:latest bash
            cd romiscan/tests/
            ./check_pipe.sh
            exit
           