# This workflow will build the Docker image, run python unit tests and checks if main features of the pipe are not broken

name: CI

on: pull_request

jobs:
    docker-build:
        runs-on: self-hosted

        steps:
         - uses: actions/checkout@v2
         - name: Build Dockerfile
           run: |
            cd docker/
            ./build.sh -t ${{ github.sha }} -b ${{ github.head_ref }} --no-cache
    
    unit-tests:
        runs-on: self-hosted
        needs: docker-build
        
        steps:
         - name: Run Unit Tests
           run: |
            ./run.sh -t ${{ github.sha }} --unittest_cmd

    feature-tests:
       runs-on: self-hosted
       needs: docker-build
        
       steps:
        - name: Run Feature Tests
          run: |
           ./run.sh -v /home/${USER}/ML_models:/home/${USER}/romiscan/tests/testdata/models/models -t ${{ github.sha }} --pipeline_test

    docker-clean:
       runs-on: self-hosted
       needs: [feature-tests, unit-tests]
       if: always()

       steps:
        - name: Remove Docker Image
          run: |
            docker image rm romiscan:${{ github.sha }}
